title: Sparks in the Dark
url: "https://garden.megu.space"
favicon: 🥬

# https://jekyllrb.com/docs/configuration/options/
timezone: America/Edmonton

# Comment out .htaccess if you're uploading to a non-Apache server such as Netlify
include: [".htaccess"]

# Remove obsidian-templates and delete the folder if you aren't using Obsidian Templates plugin
exclude: ["_includes/notes_graph.json", "obsidian-templates"]

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities or Dreamhost), set this to 'true'.
use_html_extension: true

# 'True' displays notes graph at bottom of each note
show_notes_graph: false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

permalink: slug

# Set to 'true' to generate excerpts for pages. Notes are technically pages.
page_excerpts: true

# Kramdown was changing straight quotation marks into curly. 
# This https://stackoverflow.com/questions/25596792/how-do-i-turn-off-smart-quotes-in-jekyll#25597026
# says that this should stop it from doing that
# Suggested fix  smart_quotes: ["apos", "apos", "quot", "quot"]
# This fix worked
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
plugins:
  - jekyll-last-modified-at

imagemagick:
  enabled: true
  widths:
    - 1500
    - 750
    - 0
  input_directories:
    - assets/images
  input_formats:
    - ".png"
    - ".tiff"
    - ".jpg"
    - ".jpeg"
  output_formats:
    jpg: "-quality 93% -define jpeg:dct-method=float -strip -interlace Plane" 
#    jpg: "-quality 93% -define jpeg:dct-method=float -strip -interlace Plane"
#    webp: "-quality 100%"



collections:
  notes:
    output: true
    permalink: /:slug

  pages:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
